"""Generate the :root variables of Assets/UI/Resources/Theme.uss from the design-system tokens.

Source: Tools/design/tokens.json (a copy of the Dusk Garden design system's tokens.json; update it from the artifact,
then run this script). Only the block between the `tokens:begin` / `tokens:end` markers is rewritten; hand-written
rules below it stay. Reference resolution 1080 x 1920 (PanelSettings): 1 dp = 3 px.

    python Tools/tokens_to_uss.py
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOKENS = os.path.join(ROOT, "Tools", "design", "tokens.json")
USS = os.path.join(ROOT, "Assets", "UI", "Resources", "Theme.uss")
DP = 3  # px per dp at the 1080-wide reference
THEME = "dusk"  # Act I; act themes switch only the arena for now

# Names used by the existing stylesheet, mapped onto design tokens (kept so no rule has to change at once).
LEGACY = {
    "--night": "ink",            # text on ivory fills
    "--glass": "surface-glass",
    "--glass-border": "line",
    "--ivory-60": "ivory-muted",  # solid: translucent colours did not blend reliably on Android
    "--ivory-40": "ivory-faint",
}


def px(value):
    value = str(value)
    if value.endswith("px"):
        return f"{float(value[:-2]) * DP:g}px"
    return value


def main():
    with open(TOKENS, encoding="utf-8") as f:
        tokens = json.load(f)
    colours = {}
    for token in tokens["color"]["tokens"]:
        value = token["value"]
        colours[token["name"]] = value if isinstance(value, str) else value.get(THEME, next(iter(value.values())))

    lines = ["/* tokens:begin — generated by Tools/tokens_to_uss.py from Tools/design/tokens.json; do not edit by hand */", ":root {"]
    for name, value in colours.items():
        lines.append(f"    --{name}: {value};")
    for legacy, source in LEGACY.items():
        lines.append(f"    {legacy}: {colours[source]};")
    for family in ("spacing", "radius", "size"):
        for token in tokens.get(family, {}).get("tokens", []):
            lines.append(f"    --{token['name']}: {px(token['value'])};")
    styles = {s["name"]: s for g in tokens["type"]["groups"] for s in g["styles"]}
    for name, style in styles.items():
        lines.append(f"    --type-{name}: {px(style['fontSize'])};")
    # Stylesheet aliases kept from v1 (docs/09 §5): the gutter (space-4) and the five font sizes.
    # --radius-card and --radius-button come straight from the radius tokens above.
    lines += [
        f"    --gutter: {px('16px')};",
        f"    --font-display: {px(styles['number-xl']['fontSize'])};",
        f"    --font-title: {px(styles['title']['fontSize'])};",
        f"    --font-number: {px(styles['number']['fontSize'])};",
        f"    --font-body: {px(styles['body']['fontSize'])};",
        f"    --font-caption: {px(styles['caption']['fontSize'])};",
    ]
    lines += ["}", "/* tokens:end */"]
    block = "\n".join(lines)

    with open(USS, encoding="utf-8") as f:
        uss = f.read()
    pattern = re.compile(r"/\* tokens:begin.*?/\* tokens:end \*/", re.S)
    if pattern.search(uss):
        uss = pattern.sub(block, uss)
    else:
        # First run: replace the hand-written v1 :root block.
        uss, count = re.subn(r"/\* Design tokens.*?\*/\s*:root \{.*?\}", block, uss, count=1, flags=re.S)
        if count == 0:
            sys.exit("No :root block found in Theme.uss")
    with open(USS, "w", encoding="utf-8", newline="\n") as f:
        f.write(uss)
    print(f"Theme.uss: {len(colours)} colours, theme '{THEME}'")


if __name__ == "__main__":
    main()
